make editor accessable globaly for customizing
Webmecanik/plugin-grapesjs-builder pull request #91
Opened 2021-11-29 11:24 UTC by KALA-Typo3

For adding custom blocks and changing behavior with a custom plugin

2021-11-29 12:30 UTC, RCheesley commented
@cla-bot check

Thanks for the PR @KALA-Typo3 - Assume this is a parallel PR for https://github.com/mautic/mautic/pull/10510?

2021-11-29 12:32 UTC, RCheesley requested changes
Thanks for the PRs - just a small typo suggestion on the comment. Will defer to @adiux for code review before we merge.

2021-11-29 12:32 UTC, RCheesley commented on Assets/library/js/builder.service.js
> +    // make editor accessable globaly for customizing
```suggestion
    // make editor accessible globally for customizing
``` 

I know it's only a comment, but a couple of typos to fix ;)

2021-11-30 10:29 UTC, KALA-Typo3 commented
Yes, I indeed remember posting it on a 3.x branch before. I also signed the agreement, since I want to contribute more often.

Sorry for typos, didn't double check before comitting.

2022-02-09 09:07 UTC, adiux commented
@RCheesley I guess we can close this in favor of https://github.com/mautic/mautic/pull/10781

2022-02-09 09:07 UTC, closed without merging